variables:
  DOCKER_DRIVER: overlay2
stages:
  - software


.lcg-alma9:
  image: gitlab-registry.cern.ch/sft/docker/alma9-core:${IMAGE}
  stage: software
  script:
    - dnf -y install epel-release dnf*
    - dnf -y config-manager --set-enabled crb
    - dnf -y install wget tar make  make autoconf bzip2 mc file which
    - dnf -y install libquadmath-devel || echo "NOT AVAILABLE"
    - dnf -y install glibc-static man-db  subversion git readline-devel readline-devel  openssl-devel bzip2-devel libffi-devel sqlite-devel
    - export
    - uname -a
    - TOP=$(pwd)
    - cd $TOP
    - pwd
    - ls /cvmfs


lcg-alma9-x86_64:
  variables:
    IMAGE: latest
    K8TAG: cvmfs
    CTAG: x86_64
  extends: .lcg-alma9

lcg-alma9-arm:
  variables:
    IMAGE: aarch64
    K8TAG: arm
    CTAG: arm
  extends: .lcg-alma9
